server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: sample-internal
          uri: lb://service
          predicates:
            - Path=/**
